name: Solar system Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main
            - 'feature/*'
jobs:
    Unit-Testing:
        name: unit testing
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: install node version - 18
          uses: actions/setup-node@v4
          with:
            node-version: 18
            
        - name: install dependencies
          run: npm install
        
        - name: unit testing
          run: npm test
    